image: eclipse-temurin:17-jdk

pipelines:
  default:
    - step:
        name: Build and Test
        services:
          - docker
        caches:
          - gradle
        script:
          # Install docker compose
          - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          - chmod +x /usr/local/bin/docker-compose
          - docker-compose version
          # Build and Test
          - TESTCONTAINERS_RYUK_DISABLED=true ./gradlew build --no-daemon

definitions:
  services:
    docker:
      memory: 2048
